spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot