spring:
  datasource:
    username: root
    password: mysql
    url: 'jdbc:mysql://localhost:3306/coffee'
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: 'classpath:data/schema.sql'
      data-locations: 'classpath:data/data.sql'
      mode: always