spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 20
        max-page-size: 2000

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  session:
    jdbc:
      initialize-schema: always
    timeout: 86400

hodolman:
  jwt-key: "1lwItElB4ceTGKXcPhB6Pynodfz9qt/z0DHbRlLx0lY="